### ISSUE TITLE
Issue with Laravel 10, php 8.1

### ISSUE THREAD

**Issue by Kavehrafie** [flavorly/laravel-vanilla-components#8]
The installation conflicts in Laravel 10

Problem 1
    - Root composer.json requires flavorly/laravel-vanilla-components * -> satisfiable by flavorly/laravel-vanilla-components[v0.0.1, ..., 0.0.9].
    - flavorly/laravel-vanilla-components[v0.0.1, ..., 0.0.9] require illuminate/contracts ^9.0 -> found illuminate/contracts[v9.0.0, ..., v9.52.6] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require flavorly/laravel-vanilla-components:*" to figure out if any version is installable, or "composer require flavorly/laravel-vanilla-components:^2.1" if you know which you need.

**Comment by nikuscs** [comment]
Thanks for the issue! Ill have a look into it quickly and let you know ,meanwhile if you want provide a PR bumping the version and ill tag a new release.

**Comment by zamblas** [comment]
I'm facing the same issue, but on Laravel 9
